### ISSUE TITLE
Build successfully but fail to install DOC?

### ISSUE THREAD

**Issue by jiapei100** [bradenmcd/openvrml#1]
Hi, all:

I successfully built current openvrml-git, but fail to have it installed, with the following error message, any solutions please?

> Installing with make install...
> 
> ========================= Installation results ===========================
> Making install in doc
> make[1]: Entering directory '....../openvrml/build/doc'
> make[2]: Entering directory '....../openvrml/build/doc'
> make[2]: Nothing to be done for 'install-exec-am'.
> /bin/bash ....../openvrml/install-sh -d /usr/local/share/doc/openvrml-0.18.99/manual \
>                          /usr/local/share/javadoc/openvrml-0.18.99/resources \
>                          /usr/local/share/javadoc/openvrml-0.18.99/vrml/node \
>                          /usr/local/share/javadoc/openvrml-0.18.99/vrml/field
> /usr/bin/install -c -m 644 ../../doc/manual/_.css ../../doc/manual/_.html ../../doc/manual/_.js ../../doc/manual/_.map ../../doc/manual/_.md5 ../../doc/manual/___incl.png ../../doc/manual/___inherit__graph_.png ../../doc/manual/bc_s.png ../../doc/manual/closed.png ../../doc/manual/doxygen.png ../../doc/manual/formula.repository ../../doc/manual/form__.png ../../doc/manual/graph_legend.png ../../doc/manual/inherit_graph__.png ../../doc/manual/nav_f.png ../../doc/manual/nav_h.png ../../doc/manual/open.png ../../doc/manual/tab_a.png ../../doc/manual/tab_b.png ../../doc/manual/tab_h.png ../../doc/manual/tab_s.png ../../doc/manual/OGL_sm_wht.png ../../doc/manual/x3d-white-on-black.png \
>                         /usr/local/share/doc/openvrml-0.18.99/manual
> /usr/bin/install: cannot stat '../../doc/manual/_.css': No such file or directory
> /usr/bin/install: cannot stat '../../doc/manual/_.html': No such file or directory
> /usr/bin/install: cannot stat '../../doc/manual/_.js': No such file or directory
> /usr/bin/install: cannot stat '../../doc/manual/_.map': No such file or directory
> /usr/bin/install: cannot stat '../../doc/manual/_.md5': No such file or directory
> /usr/bin/install: cannot stat '../../doc/manual/___incl.png': No such file or directory
> /usr/bin/install: cannot stat '../../doc/manual/___inherit__graph_.png': No such file or directory
> /usr/bin/install: cannot stat '../../doc/manual/bc_s.png': No such file or directory
> /usr/bin/install: cannot stat '../../doc/manual/closed.png': No such file or directory
> /usr/bin/install: cannot stat '../../doc/manual/doxygen.png': No such file or directory
> /usr/bin/install: cannot stat '../../doc/manual/formula.repository': No such file or directory
> /usr/bin/install: cannot stat '../../doc/manual/form__.png': No such file or directory
> /usr/bin/install: cannot stat '../../doc/manual/graph_legend.png': No such file or directory
> /usr/bin/install: cannot stat '../../doc/manual/inherit_graph__.png': No such file or directory
> /usr/bin/install: cannot stat '../../doc/manual/nav_f.png': No such file or directory
> /usr/bin/install: cannot stat '../../doc/manual/nav_h.png': No such file or directory
> /usr/bin/install: cannot stat '../../doc/manual/open.png': No such file or directory
> /usr/bin/install: cannot stat '../../doc/manual/tab_a.png': No such file or directory
> /usr/bin/install: cannot stat '../../doc/manual/tab_b.png': No such file or directory
> /usr/bin/install: cannot stat '../../doc/manual/tab_h.png': No such file or directory
> /usr/bin/install: cannot stat '../../doc/manual/tab_s.png': No such file or directory
> Makefile:653: recipe for target 'install-data-local' failed
> make[2]: **\* [install-data-local] Error 1
> make[2]: Leaving directory '....../openvrml/build/doc'
> Makefile:521: recipe for target 'install-am' failed
> make[1]: **\* [install-am] Error 2
> make[1]: Leaving directory '....../openvrml/build/doc'
> Makefile:551: recipe for target 'install-recursive' failed
> make: **\* [install-recursive] Error 1
> 
> ***\*  Installation failed. Aborting package creation.
> 
> Restoring overwritten files from backup...OK
> 
> Cleaning up...OK
> 
> Bye.

Cheers
Pei

**Comment by jiapei100** [comment]
Got it... you are lack of 
doc
manual

Better to push all files up here...
Close topic

Cheers

**Comment by bradenmcd** [comment]
Those files are generated. You need to `make html` before you `make install`.

This (i.e., the GitHub Issues facility) is a defect tracker for the project; not a support facility. If you have questions about building/deploying OpenVRML, please use the `openvrml-develop` mailing list.
